# Generated by Django 5.2.3 on 2025-06-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_fooditem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
