# Generated by Django 5.2.3 on 2025-07-08 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='staff',
        ),
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.ManyToManyField(related_name='company_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
